services:
  mongodb:
    image: mongo
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    ports:
      - "5555:5555"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/books-collection
    depends_on:
      - mongodb
    networks:
      - mern-network

networks:
  mern-network:
    external: true

volumes:
  mongo-data: